name: Publish

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   artifactName: "^europa.*ubuntu$"
          #   targetName: "europa"
          #   platform: "x86_64-linux"
          #   appType: "AppImage" 

          - os: windows-latest
            artifactName: "^europa.*win\\.exe$"
            targetName: "europa.exe"
            platform: "x86_64-win"
            appType: "exe" 

          # - os: macos-latest
          #   artifactName: "^europa.*darwin$"
          #   targetName: "europa"
          #   platform: "x86_64-darwin"
          #   appType: "dmg" 

    steps:
      - uses: actions/checkout@v2
      # - name: Extract tag name
      #   id: tag
      #   uses: actions/github-script@0.2.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       return context.payload.ref.replace(/refs\/tags\//, '');

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Upload applications to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: package.json
          asset_name: Europa-${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}.${{ matrix.appType }}
          tag: ${{ steps.get_version.outputs.VERSION }}
          body: "release"
          prerelease: true