name: Publish

on:
  push:
    tags:
      - v**

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifactName: "^europa.*ubuntu$"
            targetName: "europa"
            platform: "x86_64-linux"
            appType: "AppImage" 

          - os: windows-latest
            artifactName: "^europa.*win\\.exe$"
            targetName: "europa.exe"
            platform: "x86_64-win"
            appType: "exe" 

          - os: macos-latest
            artifactName: "^europa.*darwin$"
            targetName: "europa"
            platform: "x86_64-darwin"
            appType: "dmg"

    steps:
      - uses: actions/checkout@v2
      - name: Download release artifact
        id: download_release_asset
        uses: i3h/download-release-asset@v1
        with:
          owner: atenjin
          repo: europa
          tag: v0.3.20
          file: ${{ matrix.artifactName }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename & mv artifact
        run: yarn run rename

      - name: Executable artifact
        run: chmod +X europa
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'mac')

      - name: echo
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'mac')
        run: ls -al ./


      # - name: Get the version
      #   if: startsWith(matrix.os, 'win')
      #   id: get_version_win
      #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      #   shell: bash

      # - name: Get the version
      #   if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'mac')
      #   id: get_version
      #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # - name: Upload applications to release
      #   if: startsWith(matrix.os, 'win')
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: package.json
      #     asset_name: Europa-${{ steps.get_version_win.outputs.VERSION }}-${{ matrix.platform }}.${{ matrix.appType }}
      #     tag: ${{ steps.get_version_win.outputs.VERSION }}
      #     body: "release"
      #     prerelease: true

      # - name: Upload applications to release
      #   if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'mac')
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: package.json
      #     asset_name: Europa-${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}.${{ matrix.appType }}
      #     tag: ${{ steps.get_version.outputs.VERSION }}
      #     body: "release"
      #     prerelease: true